version: '1.0'
services:
  - name: db
    type: postgres
    version: 13
    configuration: StandAlone
    ports:
      - 5432
    database: postgres
    username: odoo
    userPassword: null
    remoteAccess: false
    deployTo:
      - odoo

  - name: odoo
    type: docker
    image: odoo
    version: 14
    ports:
      - 8069
      - 8071
    remoteAccess: false
    env:
      HOST: "{{=service('db').getMasterAlias()}}"
      PORT: "{{=service('db').getMainPort()}}"
      USER: odoo
      PASSWORD: "{{=service('db').get('userPassword')}}"
    volumes:
      - directory: /var/lib/odoo
      sync: true
    volumesUID: 101
    deployTo:
      - odoo

  - name: web
    type: nginx
    version: 1.19
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: odoo
    deployTo:
      - odoo

hosts:
  - name: odoo
    requirements:
      cores: 1
      memory: 1
